package com.erfeamor.cvdomain.education;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.erfeamor.cvdomain.person.Person;
import com.erfeamor.cvdomain.person.PersonRepository;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.test.web.servlet.MockMvc;

/**
 * Web-layer coverage for the education aggregate (test-plan cases C1-C17).
 */
@WebMvcTest(EducationController.class)
@AutoConfigureMockMvc(addFilters = false)
class EducationControllerTest {

    private static final String VALID_BODY = """
            {"institution":"UNED","degree":"BSc","fieldOfStudy":"Computer Science",
             "startDate":"2015-09-01","endDate":"2019-06-30"}
            """;

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private EducationRepository educationRepository;

    @MockBean
    private PersonRepository personRepository;

    private Person person() {
        return new Person("Jane Doe", "Engineer", "jane@example.com", "Remote", "Bio");
    }

    private Education education(String institution, LocalDate endDate) {
        return education(null, institution, endDate);
    }

    /**
     * The id is generated by the database, so a fixture that never touches one has a null id and
     * the contract-shape assertions cannot see the field. Set reflectively, the same way
     * ExperienceControllerTest does it for the twin resource.
     */
    private Education education(Long id, String institution, LocalDate endDate) {
        Education education = new Education(person(), institution, "BSc", "Computer Science",
                LocalDate.of(2015, 9, 1), endDate);
        if (id != null) {
            ReflectionTestUtils.setField(education, "id", id);
        }
        return education;
    }

    private void personExists() {
        given(personRepository.findById(1L)).willReturn(Optional.of(person()));
    }

    private void personAbsent() {
        given(personRepository.findById(999L)).willReturn(Optional.empty());
    }

    // C1
    @Test
    void c1ListsEducationsForAnExistingPerson() throws Exception {
        personExists();
        given(educationRepository.findByPersonIdOrderByStartDateDescIdAsc(1L))
                .willReturn(List.of(education("UNED", LocalDate.of(2019, 6, 30)),
                        education("MIT", null)));

        mockMvc.perform(get("/api/v1/people/1/educations"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].institution").value("UNED"));
    }

    // C2 — DoR 3: zero rows is an empty collection, never a 404.
    @Test
    void c2ReturnsAnEmptyArrayWhenThePersonHasNoEducations() throws Exception {
        personExists();
        given(educationRepository.findByPersonIdOrderByStartDateDescIdAsc(1L))
                .willReturn(List.of());

        mockMvc.perform(get("/api/v1/people/1/educations"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(0));
    }

    // C3
    @Test
    void c3CreatesAnEducationAndEchoesTheContractShape() throws Exception {
        personExists();
        given(educationRepository.save(any(Education.class))).willAnswer(invocation -> {
            // Typed local on purpose: invocation.getArgument(0) infers Object, which binds
            // ReflectionTestUtils.setField's (Class, String, Object) overload and blows up at
            // runtime with a ClassCastException rather than at compile time.
            Education toSave = invocation.getArgument(0);
            ReflectionTestUtils.setField(toSave, "id", 5L);
            return toSave;
        });

        mockMvc.perform(post("/api/v1/people/1/educations")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(5))
                .andExpect(jsonPath("$.institution").value("UNED"))
                .andExpect(jsonPath("$.fieldOfStudy").value("Computer Science"))
                .andExpect(jsonPath("$.endDate").value("2019-06-30"));
    }

    // C4/C5/C6 — each required field rejected on its own, so one missing @NotBlank cannot hide
    // behind another field's validation.
    @Test
    void c4RejectsAMissingInstitution() throws Exception {
        personExists();
        mockMvc.perform(post("/api/v1/people/1/educations")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"degree":"BSc","startDate":"2015-09-01"}"""))
                .andExpect(status().isBadRequest());
    }

    @Test
    void c5RejectsAMissingDegree() throws Exception {
        personExists();
        mockMvc.perform(post("/api/v1/people/1/educations")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"institution":"UNED","startDate":"2015-09-01"}"""))
                .andExpect(status().isBadRequest());
    }

    @Test
    void c6RejectsAMissingStartDate() throws Exception {
        personExists();
        mockMvc.perform(post("/api/v1/people/1/educations")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"institution":"UNED","degree":"BSc"}"""))
                .andExpect(status().isBadRequest());
    }

    // C7 — omitted optionals must serialize as JSON null, not be dropped from the payload.
    @Test
    void c7SerializesOmittedOptionalsAsNull() throws Exception {
        personExists();
        given(educationRepository.save(any(Education.class)))
                .willAnswer(invocation -> invocation.getArgument(0));

        mockMvc.perform(post("/api/v1/people/1/educations")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"institution":"UNED","degree":"BSc","startDate":"2015-09-01"}"""))
                .andExpect(status().isCreated())
                // PRESENT and null, not absent. jsonPath's doesNotExist() treats a JSON null as
                // absent, so asserting that would pass for the wrong reason -- and would keep
                // passing if someone added @JsonInclude(NON_NULL), which WOULD break the
                // contract ("absent optionals serialize as null"). Confirmed against live MySQL
                // during stage-4 QA: the body is {"fieldOfStudy":null,...,"endDate":null}.
                .andExpect(jsonPath("$.length()").value(6))
                .andExpect(jsonPath("$.fieldOfStudy").value(org.hamcrest.Matchers.nullValue()))
                .andExpect(jsonPath("$.endDate").value(org.hamcrest.Matchers.nullValue()));
    }

    // C8
    @Test
    void c8UpdatesAnEducationOwnedByThePerson() throws Exception {
        personExists();
        Education existing = education(5L, "UNED", LocalDate.of(2019, 6, 30));
        given(educationRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.of(existing));
        given(educationRepository.save(any(Education.class)))
                .willAnswer(invocation -> invocation.getArgument(0));

        mockMvc.perform(put("/api/v1/people/1/educations/5")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"institution":"MIT","degree":"MSc","fieldOfStudy":"Maths",
                                 "startDate":"2020-01-01","endDate":null}"""))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(5))
                .andExpect(jsonPath("$.institution").value("MIT"))
                .andExpect(jsonPath("$.degree").value("MSc"))
                .andExpect(jsonPath("$.endDate").value(org.hamcrest.Matchers.nullValue()));
    }

    // C9
    @Test
    void c9RejectsAnUpdateMissingARequiredField() throws Exception {
        personExists();
        mockMvc.perform(put("/api/v1/people/1/educations/5")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"degree":"MSc","startDate":"2020-01-01"}"""))
                .andExpect(status().isBadRequest());
    }

    // C10
    @Test
    void c10DeletesAnEducationOwnedByThePerson() throws Exception {
        personExists();
        Education existing = education("UNED", null);
        given(educationRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.of(existing));

        mockMvc.perform(delete("/api/v1/people/1/educations/5"))
                .andExpect(status().isNoContent())
                .andExpect(content().string(""));
        verify(educationRepository).delete(existing);
    }

    // C11-C14 — DoR 4: the person is resolved first, so an unknown person 404s on every verb
    // before the child lookup can run.
    @Test
    void c11UnknownPersonOnGet() throws Exception {
        personAbsent();
        mockMvc.perform(get("/api/v1/people/999/educations")).andExpect(status().isNotFound());
    }

    @Test
    void c12UnknownPersonOnPost() throws Exception {
        personAbsent();
        mockMvc.perform(post("/api/v1/people/999/educations")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isNotFound());
        verify(educationRepository, never()).save(any());
    }

    @Test
    void c13UnknownPersonOnPut() throws Exception {
        personAbsent();
        mockMvc.perform(put("/api/v1/people/999/educations/5")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isNotFound());
    }

    @Test
    void c14UnknownPersonOnDelete() throws Exception {
        personAbsent();
        mockMvc.perform(delete("/api/v1/people/999/educations/5"))
                .andExpect(status().isNotFound());
        verify(educationRepository, never()).delete(any());
    }

    // C15 — DoR 1: deleting an absent id is a 404, not an idempotent 204.
    @Test
    void c15DeletingAnAbsentEducationIs404NotSilent204() throws Exception {
        personExists();
        given(educationRepository.findByIdAndPersonId(9999L, 1L)).willReturn(Optional.empty());

        mockMvc.perform(delete("/api/v1/people/1/educations/9999"))
                .andExpect(status().isNotFound());
        verify(educationRepository, never()).delete(any());
    }

    // C16 — DoR 2, the IDOR case. The scoped lookup returns empty for another person's row, so
    // both verbs 404 and the victim's row is never touched.
    @Test
    void c16CrossPersonUpdateIs404AndLeavesTheVictimRowUntouched() throws Exception {
        personExists();
        given(educationRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.empty());

        mockMvc.perform(put("/api/v1/people/1/educations/5")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isNotFound());
        verify(educationRepository, never()).save(any());
    }

    @Test
    void c16CrossPersonDeleteIs404AndLeavesTheVictimRowUntouched() throws Exception {
        personExists();
        given(educationRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.empty());

        mockMvc.perform(delete("/api/v1/people/1/educations/5"))
                .andExpect(status().isNotFound());
        verify(educationRepository, never()).delete(any());
    }

    // C17 — the whole response object, field for field. Catches a leaked personId or a nested
    // person object, which the per-field assertions above would not.
    @Test
    void c17ResponseMatchesTheContractShapeExactly() throws Exception {
        personExists();
        given(educationRepository.findByPersonIdOrderByStartDateDescIdAsc(1L))
                .willReturn(List.of(education(5L, "UNED", LocalDate.of(2019, 6, 30))));

        mockMvc.perform(get("/api/v1/people/1/educations"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].length()").value(6))
                .andExpect(jsonPath("$[0].id").value(5))
                .andExpect(jsonPath("$[0].institution").value("UNED"))
                .andExpect(jsonPath("$[0].degree").value("BSc"))
                .andExpect(jsonPath("$[0].fieldOfStudy").value("Computer Science"))
                .andExpect(jsonPath("$[0].startDate").value("2015-09-01"))
                .andExpect(jsonPath("$[0].endDate").value("2019-06-30"))
                .andExpect(jsonPath("$[0].person").doesNotExist())
                .andExpect(jsonPath("$[0].personId").doesNotExist());
    }

    // Ordering is the repository's job (contract § Ordering). This asserts the controller does
    // not re-sort or otherwise second-guess it -- it must pass the repository's order straight
    // through, which is what makes the repository the single source of truth.
    @Test
    void passesTheRepositoryOrderThroughUnchanged() throws Exception {
        personExists();
        Education newer = education("MIT", null);
        Education older = education("UNED", LocalDate.of(2019, 6, 30));
        given(educationRepository.findByPersonIdOrderByStartDateDescIdAsc(1L))
                .willReturn(List.of(newer, older));

        mockMvc.perform(get("/api/v1/people/1/educations"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].institution").value("MIT"))
                .andExpect(jsonPath("$[1].institution").value("UNED"));
        verify(educationRepository).findByPersonIdOrderByStartDateDescIdAsc(eq(1L));
    }
}
