package com.erfeamor.cvdomain.project;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.erfeamor.cvdomain.person.Person;
import com.erfeamor.cvdomain.person.PersonRepository;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.test.web.servlet.MockMvc;

/**
 * Web-layer coverage for the project aggregate (test-plan cases C1-C16, plus the T-107 guard and
 * the ordering pass-through).
 */
@WebMvcTest(ProjectController.class)
@AutoConfigureMockMvc(addFilters = false)
class ProjectControllerTest {

    private static final String VALID_BODY = """
            {"name":"cv-project","description":"An interactive CV",
             "repoUrl":"https://github.com/erfeamor/cv-project",
             "startDate":"2026-07-01","endDate":null}
            """;

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private ProjectRepository projectRepository;

    @MockBean
    private PersonRepository personRepository;

    private Person person() {
        return new Person("Jane Doe", "Engineer", "jane@example.com", "Remote", "Bio");
    }

    private Project project(String name, LocalDate startDate) {
        return project(null, name, startDate);
    }

    /**
     * The id is generated by the database, so a fixture that never touches one has a null id and
     * the contract-shape assertions cannot see the field. Set reflectively, the same way the
     * sibling resources' tests do it.
     */
    private Project project(Long id, String name, LocalDate startDate) {
        Project project = new Project(person(), name, "An interactive CV",
                "https://github.com/erfeamor/cv-project", startDate, null);
        if (id != null) {
            ReflectionTestUtils.setField(project, "id", id);
        }
        return project;
    }

    private void personExists() {
        given(personRepository.findById(1L)).willReturn(Optional.of(person()));
    }

    private void personAbsent() {
        given(personRepository.findById(999L)).willReturn(Optional.empty());
    }

    /** Echoes back whatever was handed to save(), the way a real repository would. */
    private void saveEchoes() {
        given(projectRepository.save(any(Project.class)))
                .willAnswer(invocation -> invocation.getArgument(0));
    }

    // C1
    @Test
    void c1ListsProjectsForAnExistingPerson() throws Exception {
        personExists();
        given(projectRepository.findByPersonIdOrdered(1L))
                .willReturn(List.of(project("cv-project", LocalDate.of(2026, 7, 1)),
                        project("older", LocalDate.of(2020, 1, 1))));

        mockMvc.perform(get("/api/v1/people/1/projects"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].name").value("cv-project"));
    }

    // C2 — DoR 3: zero rows is an empty collection, never a 404.
    @Test
    void c2ReturnsAnEmptyArrayWhenThePersonHasNoProjects() throws Exception {
        personExists();
        given(projectRepository.findByPersonIdOrdered(1L)).willReturn(List.of());

        mockMvc.perform(get("/api/v1/people/1/projects"))
                .andExpect(status().isOk())
                .andExpect(content().json("[]"))
                .andExpect(jsonPath("$.length()").value(0));
    }

    // C3
    @Test
    void c3CreatesAProjectAndEchoesTheContractShape() throws Exception {
        personExists();
        given(projectRepository.save(any(Project.class))).willAnswer(invocation -> {
            // Typed local on purpose: invocation.getArgument(0) infers Object, which binds
            // ReflectionTestUtils.setField's (Class, String, Object) overload and blows up at
            // runtime with a ClassCastException rather than at compile time.
            Project toSave = invocation.getArgument(0);
            ReflectionTestUtils.setField(toSave, "id", 5L);
            return toSave;
        });

        mockMvc.perform(post("/api/v1/people/1/projects")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(5))
                .andExpect(jsonPath("$.name").value("cv-project"))
                .andExpect(jsonPath("$.repoUrl").value("https://github.com/erfeamor/cv-project"))
                .andExpect(jsonPath("$.startDate").value("2026-07-01"))
                .andExpect(jsonPath("$.endDate").value(Matchers.nullValue()));
    }

    // C4 — name is the ONLY required field, so it is the only one that can produce a 400.
    @Test
    void c4RejectsAMissingName() throws Exception {
        personExists();
        mockMvc.perform(post("/api/v1/people/1/projects")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"description":"no name here","startDate":"2026-07-01"}"""))
                .andExpect(status().isBadRequest());
        verify(projectRepository, never()).save(any());
    }

    @Test
    void c4RejectsABlankName() throws Exception {
        personExists();
        mockMvc.perform(post("/api/v1/people/1/projects")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"name":"   "}"""))
                .andExpect(status().isBadRequest());
        verify(projectRepository, never()).save(any());
    }

    /**
     * C5 / DoR 6 — a name-only POST is a legitimate request shape here and has no analogue in the
     * sibling resources: {@code start_date} and {@code end_date} are nullable in this table only.
     * This is the test that fails first if someone copies T-101/T-102's {@code @NotNull} onto
     * {@code startDate}, which is the primary coverage risk on this task.
     *
     * <p>The four optionals are asserted PRESENT and null, not absent. jsonPath's
     * {@code doesNotExist()} treats a JSON null as absent, so asserting that would pass for the
     * wrong reason — and would keep passing under {@code @JsonInclude(NON_NULL)}, which WOULD
     * break the contract's "absent optionals serialize as null".
     */
    @Test
    void c5AcceptsAPostCarryingOnlyTheName() throws Exception {
        personExists();
        saveEchoes();

        mockMvc.perform(post("/api/v1/people/1/projects")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"name":"name only"}"""))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.length()").value(6))
                .andExpect(jsonPath("$.name").value("name only"))
                .andExpect(jsonPath("$.description").value(Matchers.nullValue()))
                .andExpect(jsonPath("$.repoUrl").value(Matchers.nullValue()))
                .andExpect(jsonPath("$.startDate").value(Matchers.nullValue()))
                .andExpect(jsonPath("$.endDate").value(Matchers.nullValue()));
    }

    // C6
    @Test
    void c6UpdatesAProjectOwnedByThePerson() throws Exception {
        personExists();
        Project existing = project(5L, "cv-project", LocalDate.of(2026, 7, 1));
        given(projectRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.of(existing));
        saveEchoes();

        mockMvc.perform(put("/api/v1/people/1/projects/5")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"name":"renamed","description":"new blurb",
                                 "repoUrl":"https://example.test/repo",
                                 "startDate":"2025-01-01","endDate":"2025-12-31"}"""))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(5))
                .andExpect(jsonPath("$.name").value("renamed"))
                .andExpect(jsonPath("$.description").value("new blurb"))
                // repoUrl and startDate are asserted because they are the two lines most easily
                // dropped from the controller's copy block; without them the suite stays green
                // while PUT silently stops replacing this aggregate's highest-risk field.
                .andExpect(jsonPath("$.repoUrl").value("https://example.test/repo"))
                .andExpect(jsonPath("$.startDate").value("2025-01-01"))
                .andExpect(jsonPath("$.endDate").value("2025-12-31"));
    }

    /** PUT replaces (§ Non-goals rules out PATCH), so omitted optionals become null. */
    @Test
    void c6UpdateReplacesRatherThanPatches() throws Exception {
        personExists();
        Project existing = project(5L, "cv-project", LocalDate.of(2026, 7, 1));
        given(projectRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.of(existing));
        saveEchoes();

        mockMvc.perform(put("/api/v1/people/1/projects/5")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"name":"renamed"}"""))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.repoUrl").value(Matchers.nullValue()))
                .andExpect(jsonPath("$.startDate").value(Matchers.nullValue()));
    }

    // C7
    @Test
    void c7RejectsAnUpdateMissingTheName() throws Exception {
        personExists();
        mockMvc.perform(put("/api/v1/people/1/projects/5")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"description":"still no name"}"""))
                .andExpect(status().isBadRequest());
        verify(projectRepository, never()).save(any());
    }

    // C8
    @Test
    void c8DeletesAProjectOwnedByThePerson() throws Exception {
        personExists();
        Project existing = project("cv-project", null);
        given(projectRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.of(existing));

        mockMvc.perform(delete("/api/v1/people/1/projects/5"))
                .andExpect(status().isNoContent())
                .andExpect(content().string(""));
        verify(projectRepository).delete(existing);
    }

    // C9-C12 — DoR 4: the person is resolved first, so an unknown person 404s on every verb
    // before the child lookup can run.
    @Test
    void c9UnknownPersonOnGet() throws Exception {
        personAbsent();
        mockMvc.perform(get("/api/v1/people/999/projects")).andExpect(status().isNotFound());
    }

    @Test
    void c10UnknownPersonOnPost() throws Exception {
        personAbsent();
        mockMvc.perform(post("/api/v1/people/999/projects")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isNotFound());
        verify(projectRepository, never()).save(any());
    }

    @Test
    void c11UnknownPersonOnPut() throws Exception {
        personAbsent();
        mockMvc.perform(put("/api/v1/people/999/projects/5")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isNotFound());
        verify(projectRepository, never()).save(any());
    }

    @Test
    void c12UnknownPersonOnDelete() throws Exception {
        personAbsent();
        mockMvc.perform(delete("/api/v1/people/999/projects/5"))
                .andExpect(status().isNotFound());
        verify(projectRepository, never()).delete(any());
    }

    // C13 — DoR 1: deleting an absent id is a 404, not an idempotent 204.
    @Test
    void c13DeletingAnAbsentProjectIs404NotSilent204() throws Exception {
        personExists();
        given(projectRepository.findByIdAndPersonId(9999L, 1L)).willReturn(Optional.empty());

        mockMvc.perform(delete("/api/v1/people/1/projects/9999"))
                .andExpect(status().isNotFound());
        verify(projectRepository, never()).delete(any());
    }

    // C14 — DoR 2, the IDOR case. The scoped lookup returns empty for another person's row, so
    // both verbs 404 and the victim's row is never touched.
    @Test
    void c14CrossPersonUpdateIs404AndLeavesTheVictimRowUntouched() throws Exception {
        personExists();
        given(projectRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.empty());

        mockMvc.perform(put("/api/v1/people/1/projects/5")
                        .contentType(MediaType.APPLICATION_JSON).content(VALID_BODY))
                .andExpect(status().isNotFound());
        verify(projectRepository, never()).save(any());
    }

    @Test
    void c14CrossPersonDeleteIs404AndLeavesTheVictimRowUntouched() throws Exception {
        personExists();
        given(projectRepository.findByIdAndPersonId(5L, 1L)).willReturn(Optional.empty());

        mockMvc.perform(delete("/api/v1/people/1/projects/5"))
                .andExpect(status().isNotFound());
        verify(projectRepository, never()).delete(any());
    }

    /**
     * C15 / DoR 5 — {@code repoUrl} carries NO format validation. The contract states only
     * "Required: {@code name}" and imposes no format on this field anywhere, so an arbitrary
     * string is a valid value. A {@code @URL} or {@code @Pattern} would narrow the contract
     * without a contract change; this test is what makes that ruling executable rather than a
     * comment.
     */
    @Test
    void c15AcceptsANonUrlRepoUrl() throws Exception {
        personExists();
        saveEchoes();

        mockMvc.perform(post("/api/v1/people/1/projects")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"name":"cv-project","repoUrl":"not-a-url"}"""))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.repoUrl").value("not-a-url"));
    }

    // C16 — the whole response object, field for field. Catches a leaked personId or a nested
    // person object, which the per-field assertions above would not.
    @Test
    void c16ResponseMatchesTheContractShapeExactly() throws Exception {
        personExists();
        given(projectRepository.findByPersonIdOrdered(1L))
                .willReturn(List.of(project(5L, "cv-project", LocalDate.of(2026, 7, 1))));

        mockMvc.perform(get("/api/v1/people/1/projects"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].length()").value(6))
                .andExpect(jsonPath("$[0].id").value(5))
                .andExpect(jsonPath("$[0].name").value("cv-project"))
                .andExpect(jsonPath("$[0].description").value("An interactive CV"))
                .andExpect(jsonPath("$[0].repoUrl")
                        .value("https://github.com/erfeamor/cv-project"))
                .andExpect(jsonPath("$[0].startDate").value("2026-07-01"))
                .andExpect(jsonPath("$[0].endDate").value(Matchers.nullValue()))
                .andExpect(jsonPath("$[0].person").doesNotExist())
                .andExpect(jsonPath("$[0].personId").doesNotExist());
    }

    /**
     * The T-107 guard. A client-supplied id in a POST body must never reach the repository.
     *
     * <p>Not a cosmetic "the server assigns ids" rule. {@code Project.id} is a private field with
     * no setter, but Jackson's INFER_PROPERTY_MUTATORS binds it anyway — verified empirically, a
     * body carrying {@code "id":999} deserializes to {@code getId() == 999}. A non-null id makes
     * Spring Data's {@code save()} take the {@code merge()} branch instead of {@code persist()},
     * and because {@code create} has already set the owning person, the resulting UPDATE
     * reassigns SOMEONE ELSE'S ROW to the caller: person 2's project row is overwritten and handed
     * to person 1, with a 201 and the victim's id in the response.
     *
     * <p>That is the same cross-person write DoR 2 scopes PUT and DELETE against, arriving through
     * the one verb that has no existing row to scope to.
     *
     * <p><strong>The save() stub is deliberate and is the whole point.</strong> T-101 shipped a
     * version of this test that asserted the permissive behaviour and passed because it mocked
     * {@code save()} — it measured the mock, not the code. Here the mock echoes the entity back
     * exactly as a real repository would, so with the guard removed this test observes a real 201
     * carrying {@code "id":999}; it can only go green because the request is rejected before the
     * repository is reached.
     */
    @Test
    void rejectsAClientSuppliedIdInsteadOfMergingOverAnExistingRow() throws Exception {
        personExists();
        saveEchoes();

        mockMvc.perform(post("/api/v1/people/1/projects")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"id":999,"name":"cv-project"}"""))
                .andExpect(status().isBadRequest());
        verify(projectRepository, never()).save(any());
    }

    /**
     * Ordering is the repository's job (contract § Ordering). This asserts the controller does not
     * re-sort or otherwise second-guess it — it must pass the repository's order straight through,
     * which is what makes the repository the single source of truth. The NULL placement itself is
     * asserted against a real database in ProjectRepositoryTest; a mocked repository cannot prove
     * it.
     */
    @Test
    void passesTheRepositoryOrderThroughUnchanged() throws Exception {
        personExists();
        given(projectRepository.findByPersonIdOrdered(1L))
                .willReturn(List.of(project("newer", LocalDate.of(2026, 7, 1)),
                        project("older", LocalDate.of(2020, 1, 1)),
                        project("undated", null)));

        mockMvc.perform(get("/api/v1/people/1/projects"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].name").value("newer"))
                .andExpect(jsonPath("$[1].name").value("older"))
                .andExpect(jsonPath("$[2].name").value("undated"));
        verify(projectRepository).findByPersonIdOrdered(eq(1L));
    }
}
